Controllers/VolunteersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project.Models;

namespace Project.Controllers
{
    public class VolunteersController : Controller
    {
        private readonly ProjectContext _context;

        public VolunteersController(ProjectContext context)
        {
            _context = context;    
        }

        // GET: Volunteers
        // Requires using Microsoft.AspNetCore.Mvc.Rendering;
        public async Task<IActionResult> Index(string approvalStatus, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> statusQuery = from m in _context.Volunteer
                                            orderby m.ApprovalStatus
                                            select m.ApprovalStatus;

            var volunteers = from m in _context.Volunteer
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                volunteers = volunteers.Where(s => s.FirstName.Contains(searchString) || s.LastName.Contains(searchString));
            }


            if (!String.IsNullOrEmpty(approvalStatus))
            {
                volunteers = volunteers.Where(x => x.ApprovalStatus == approvalStatus);
            }

            var approvalStatusVM = new ApprovalStatusViewModel();
            approvalStatusVM.status = new SelectList(await statusQuery.Distinct().ToListAsync());
            approvalStatusVM.volunteer = await volunteers.ToListAsync();

            return View(approvalStatusVM);
        }

        // GET: Volunteers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var volunteer = await _context.Volunteer
                .SingleOrDefaultAsync(m => m.VolunteerID == id);
            if (volunteer == null)
            {
                return NotFound();
            }

            return View(volunteer);
        }

        // GET: Volunteers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Volunteers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VolunteerID,LastName,FirstName,UserName,Availability,Address,PhoneNumber,Email,Education,DriverLicense,SocialSecurity,ApprovalStatus")] Volunteer volunteer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(volunteer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(volunteer);
        }

        // GET: Volunteers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var volunteer = await _context.Volunteer.SingleOrDefaultAsync(m => m.VolunteerID == id);
            if (volunteer == null)
            {
                return NotFound();
            }
            return View(volunteer);
        }

        // POST: Volunteers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VolunteerID,LastName,FirstName,UserName,Availability,Address,PhoneNumber,Email,Education,DriverLicense,SocialSecurity,ApprovalStatus")] Volunteer volunteer)
        {
            if (id != volunteer.VolunteerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(volunteer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VolunteerExists(volunteer.VolunteerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(volunteer);
        }

        // GET: Volunteers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var volunteer = await _context.Volunteer
                .SingleOrDefaultAsync(m => m.VolunteerID == id);
            if (volunteer == null)
            {
                return NotFound();
            }

            return View(volunteer);
        }

        // POST: Volunteers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var volunteer = await _context.Volunteer.SingleOrDefaultAsync(m => m.VolunteerID == id);
            _context.Volunteer.Remove(volunteer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool VolunteerExists(int id)
        {
            return _context.Volunteer.Any(e => e.VolunteerID == id);
        }
    }
}

Views/Volunteers/Create.cshtml
@model Project.Models.Volunteer

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Volunteer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="UserName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Availability" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Availability" class="form-control" />
                <span asp-validation-for="Availability" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Education" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Education" class="form-control" />
                <span asp-validation-for="Education" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DriverLicense" class="col-md-2 control-label">Driver Licenses is on file?</label>
            <div class="col-md-10">

                "How do i pass the information from the radio buttons?"
                
                <input asp-for="DriverLicense" class="form-control" />
                <span asp-validation-for="DriverLicense" class="text-danger"></span>

                <label class="radio-inline"><input type="radio" name="yesLicense">Yes</label>
                <label class="radio-inline"><input type="radio" name="noLicense">No</label>
            </div>
        </div>
        <div class="form-group">
           
            <label asp-for="SocialSecurity" class="col-md-2 control-label">Social Security is on file?</label>
            <div class="col-md-10">
                <input asp-for="SocialSecurity" class="form-control" />
                <span asp-validation-for="SocialSecurity" class="text-danger"></span>

                <label class="radio-inline"><input type="radio" name="yesLicense">Yes</label>
                <label class="radio-inline"><input type="radio" name="noLicense">No</label>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ApprovalStatus" class="col-md-2 control-label"></label>
            <div class="col-md-10">

                <input asp-for="ApprovalStatus" class="form-control" />
                <span asp-validation-for="ApprovalStatus" class="text-danger"></span>

                <select class="form-control" id="status">
                    <option>Approved</option>
                    <option>Pending Approval</option>
                    <option>Disapproved</option>
                    <option>Inactive</option>
                </select>

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Volunteers/Delete.cshtml
@model Project.Models.Volunteer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Volunteer</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="VolunteerID" />
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Availability)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Availability)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DriverLicense)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriverLicense)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SocialSecurity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SocialSecurity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApprovalStatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Views/Volunteers/Details.cshtml
@model Project.Models.Volunteer

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Volunteer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Availability)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Availability)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApprovalStatus)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DriverLicense)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriverLicense)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SocialSecurity)
            There is a copy of volunteer's driver licenses on file?
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SocialSecurity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApprovalStatus)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.VolunteerID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Volunteers/Edit.cshtml
@model Project.Models.Volunteer

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Volunteer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="VolunteerID" />
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="UserName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Availability" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Availability" class="form-control" />
                <span asp-validation-for="Availability" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Education" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Education" class="form-control" />
                <span asp-validation-for="Education" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DriverLicense" class="col-md-2 control-label">Driver Licenses is on file?</label>
            <div class="col-md-10">

                "How do i pass the information from the radio buttons?"

                <input asp-for="DriverLicense" class="form-control" />
                <span asp-validation-for="DriverLicense" class="text-danger"></span>

                <label class="radio-inline"><input type="radio" name="yesLicense">Yes</label>
                <label class="radio-inline"><input type="radio" name="noLicense">No</label>
            </div>
        </div>
        <div class="form-group">

            <label asp-for="SocialSecurity" class="col-md-2 control-label">Social Security is on file?</label>
            <div class="col-md-10">
                <input asp-for="SocialSecurity" class="form-control" />
                <span asp-validation-for="SocialSecurity" class="text-danger"></span>

                <label class="radio-inline"><input type="radio" name="yesLicense">Yes</label>
                <label class="radio-inline"><input type="radio" name="noLicense">No</label>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ApprovalStatus" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ApprovalStatus" class="form-control" />
                <span asp-validation-for="ApprovalStatus" class="text-danger"></span>

                <select class="form-control" id="status">
                    <option>Approved</option>
                    <option>Pending Approval</option>
                    <option>Disapproved</option>
                    <option>Inactive</option>
                </select>

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Volunteers/Index.cshtml

@model Project.Models.ApprovalStatusViewModel


@{
    ViewData["Title"] = "Index";
}

<h2>Volunteers</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Volunteers" asp-action="Index" method="get">
    <p>
        <select asp-for="ApprovalStatus" asp-items="Model.status">
            <option value="">All</option>
            <option value="Approved/Pending Approval">Approved/Pending Approval</option>
            <option value="Approved">Approved</option>
            <option value="Pending Approval">Pending Approval</option>
            <option value="Disapproved">Disapproved</option>
            <option value="Inactive">Inactive</option>
        </select>

        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.volunteer[0].LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.volunteer[0].FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.volunteer[0].UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.volunteer[0].ApprovalStatus)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.volunteer) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApprovalStatus)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VolunteerID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.VolunteerID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.VolunteerID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>